airtable_api_key = "patdNMT424EkcYEgR.df1fcd9d087d6977be07d02c2b53bdd64afffc583e736a5be174aec174083df1"
airtable_base_id = "appvpfPx6TClv49Mj"
airtable_table_assessment = "Assessments"
airtable_table_milestones = "Milestones"
