# when using community cloud, this file is NOT read
#       you must put this info into the streamlit system directly

[auth]
cookie_secret = "1MaYXdyhVwf4E3gytcZWIHVzTRK1liWN"
client_id = "Bn7wDhMM0WzVJXnawN5J7N09qpdvNsjq"
client_secret = "v3NrhxjVPflq9ODTyhcRGrqVIf8efwiXqWiZdAzsn8qGgbZrT116q36Ph0HXfGMf"
server_metadata_url = "https://impact-readiness.ca.auth0.com/.well-known/openid-configuration"  # fmt: skip
client_kwargs = { "prompt" = "login" }
redirect_uri = "https://blank-app-uz4c6bof36.streamlit.app/Login/oauth2callback"

[general]
airtable_api_key = "patdNMT424EkcYEgR.df1fcd9d087d6977be07d02c2b53bdd64afffc583e736a5be174aec174083df1"
airtable_base_id = "appvpfPx6TClv49Mj"
airtable_table_assessment = "IRL 0.31"
airtable_table_data = "IRL 0.31 Data"
airtable_table_milestones = "MIRL 1.0"
airtable_table_assessors = "ASSESSORs"
airtable_table_reviewers = "REVIEWERs"
airtable_table_support = "Support Organizations"
airtable_table_ventures = "Ventures"
airtable_table_projects = "Projects"
